"""Task model for todo application.

This module defines the Task entity with validation rules for title and description.
"""

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Task:
    """Represents a single todo item.

    Attributes:
        id: Unique integer identifier (auto-generated by TaskManager)
        title: Task title (1-200 characters, required)
        description: Task description (max 1000 characters, optional)
        completed: Completion status (default: False)
        created_at: Creation timestamp (auto-generated)
    """

    id: int
    title: str
    description: str = ""
    completed: bool = False
    created_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Validate task attributes after initialization.

        Raises:
            ValueError: If title or description violate constraints
        """
        # Validate title
        if not self.title or not self.title.strip():
            raise ValueError("Title cannot be empty")

        # Strip whitespace from title
        self.title = self.title.strip()

        if len(self.title) > 200:
            raise ValueError("Title must be 200 characters or less")

        # Validate description
        if self.description is None:
            self.description = ""

        if len(self.description) > 1000:
            raise ValueError("Description must be 1000 characters or less")

    def __str__(self) -> str:
        """Return string representation of task."""
        status = "✓" if self.completed else " "
        desc_preview = self.description[:50] + "..." if len(self.description) > 50 else self.description
        return f"[{status}] Task #{self.id}: {self.title}" + (f"\n    {desc_preview}" if desc_preview else "")
